[system]
    env="dev"       # pro dev oa local
    post=8888
    oss-type="local"
    use-multipoint=false   #多点登录

[jwt]
  signing-key='ginf'
# captcha configuration
[captcha]
    key-long= 6
    img-width=240
    img-height= 80

# casbin configuration
[casbin]
  model-path='./resource/rbac_model.conf'
# email configuration
[email]
  to= 'xxx@qq.com'
  port= 465
  from='xxx@163.com'
  host='smtp.163.com'
  is-ssl=true
  secret='xxx'
  nickname='test'
  ginf-email="ginf_email"

  # local configuration
[local]
    path='uploads/file'
